#!/bin/bash

rm -f ~/.bash_profile ~/.bashrc ~/.gitignore_global ~/.ratpoisonrc ~/.speedswapper ~/.vimperatorrc ~/.vimrc ~/.Xdefaults ~/.xinitrc ~/.xombrero.conf ~/.Xresources ~/.zlogin ~/.zshrc 
ln -s yadotfiles/bash_profile ~/.bash_profile
ln -s yadotfiles/bashrc ~/.bashrc
ln -s yadotfiles/gitignore_global ~/.gitignore_global
ln -s yadotfiles/ratpoisonrc ~/.ratpoisonrc
ln -s yadotfiles/speedswapper ~/.speedswapper
ln -s yadotfiles/vimperatorrc ~/.vimperatorrc
ln -s yadotfiles/vimrc ~/.vimrc
ln -s yadotfiles/Xdefaults ~/.Xdefaults
ln -s yadotfiles/xinitrc ~/.xinitrc
ln -s yadotfiles/xombrero.conf ~/.xombrero.conf
ln -s yadotfiles/Xresources ~/.Xresources
ln -s yadotfiles/zlogin ~/.zlogin
ln -s yadotfiles/zshrc ~/.zshrc
