#!/bin/bash

rm -f ~/.gitignore_global ~/.speedswapper ~/.vimperatorrc ~/.vimrc ~/.Xdefaults ~/.xinitrc ~/.xombrero.conf ~/.Xresources ~/.zlogin ~/.zshrc ~/.gopaths
ln -s yadotfiles/gitignore_global ~/.gitignore_global
ln -s yadotfiles/speedswapper2 ~/.speedswapper2
ln -s yadotfiles/vimperatorrc ~/.vimperatorrc
ln -s yadotfiles/vimrc ~/.vimrc
ln -s yadotfiles/Xdefaults ~/.Xdefaults
ln -s yadotfiles/xinitrc ~/.xinitrc
ln -s yadotfiles/xombrero.conf ~/.xombrero.conf
ln -s yadotfiles/Xresources ~/.Xresources
ln -s yadotfiles/zlogin ~/.zlogin
ln -s yadotfiles/zshrc ~/.zshrc
ln -s yadotfiles/gopaths ~/.gopaths
